JudgeMyPhoto/ViewModels/Category/CategoryListItemViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Marcware.JudgeMyPhoto.ViewModels.Category
{
    public class CategoryListItemViewModel
    {
        /// <summary>
        /// Category id
        /// </summary>        
        [Display(Name = "Category id")]
        public int CategoryId { get; set; }

        /// <summary>
        /// Category text
        /// </summary>
        [Display(Name = "Name")]
        public string CategoryName { get; set; }

        /// <summary>
        /// Status code
        /// </summary>
        public string StatusCode { get; set; }

        /// <summary>
        /// Status code as held in the database
        /// </summary>
        [Display(Name = "Status")]
        public string StatusCodeText { get; set; }

        /// <summary>
        /// Long status text
        /// </summary>
        [Display(Name = "Status text")]        
        public string StatusText { get; set; }
    }
}

JudgeMyPhoto/ViewModels/Category/CategoryListViewModel.cs
using System.Collections.Generic;

namespace Marcware.JudgeMyPhoto.ViewModels.Category
{
    public class CategoryListViewModel
    {
        public List<CategoryListItemViewModel> Items { get; set; }
    }
}

JudgeMyPhoto/ViewModels/Category/CategoryViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Marcware.JudgeMyPhoto.ViewModels.Category
{
    public class CategoryViewModel
    {
        /// <summary>
        /// Category id
        /// </summary>        
        [Display(Name = "Category id")]
        public int CategoryId { get; set; }

        /// <summary>
        /// Category text
        /// </summary>
        [Display(Name = "Name")]
        [Required(ErrorMessage = "Fool. A category must have a description.")]
        public string CategoryName { get; set; }

        /// <summary>
        /// Status code as held in the database
        /// </summary>
        [Display(Name = "Status")]
        [StringLength(2)]
        [MaxLength(2)]
        [Required(ErrorMessage = "A category must have a status")]
        public string StatusCode { get; set; }

        /// <summary>
        /// Long status text
        /// </summary>
        [Display(Name = "Status text")]
        [StringLength(200)]
        [MaxLength(200)]
        [Required(ErrorMessage = "Now don't be silly. This can't be empty.")]
        public string StatusText { get; set; }

        /// <summary>
        /// Theme used in the category when giving anonymous names to the photos
        /// </summary>
        [Display(Name = "Photo naming theme")]
        [StringLength(3)]
        [MaxLength(3)]
        [Required(ErrorMessage = "A theme must be specified")]
        public string PhotoNamingThemeCode { get; set; }

        /// <summary>
        /// Collection of all status types available
        /// </summary>
        public IEnumerable<KeyValuePair<string, string>> StatusCodeTypes { get; set; }


        /// <summary>
        /// Collection of all photo naming themes available
        /// </summary>
        public IEnumerable<KeyValuePair<string, string>> PhotoNamingThemeTypes { get; set; }
    }
}

JudgeMyPhoto/ViewModels/Category/DeleteCategoryViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Marcware.JudgeMyPhoto.ViewModels.Category
{
    public class DeleteCategoryViewModel
    {
        /// <summary>
        /// Category id
        /// </summary>        
        [Display(Name = "Category id")]
        public int CategoryId { get; set; }

        /// <summary>
        /// Category text
        /// </summary>
        [Display(Name = "Name")]
        public string CategoryName { get; set; }
    }
}

JudgeMyPhoto/Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Marcware.JudgeMyPhoto.Classes;
using Marcware.JudgeMyPhoto.Constants;
using Marcware.JudgeMyPhoto.Entities.Context;
using Marcware.JudgeMyPhoto.Entities.Models;
using Marcware.JudgeMyPhoto.ExtensionMethods;
using Marcware.JudgeMyPhoto.ViewModelMappers.Photo;
using Marcware.JudgeMyPhoto.ViewModels.Photo;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Marcware.JudgeMyPhoto.Controllers
{
    [Authorize(Roles = JudgeMyPhotoRoles.Photographer)]
    public class PhotosController : Controller
    {
        #region Constructor
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly JudgeMyPhotoDbContext _db;

        public PhotosController(UserManager<ApplicationUser> userManager, JudgeMyPhotoDbContext db)
        {
            _userManager = userManager;
            _db = db;
        }
        #endregion

        #region Submit photos
        public async Task<IActionResult> Submit(int id)
        {
            ProcessResult<bool> categoryStatus = await CategoryIsInRequiredStatus(id, CategoryStatusCodes.SubmittingPhotos);

            if (categoryStatus.Success)
            {
                SubmitPhotosViewModel viewModel = new SubmitPhotosViewModel();
                viewModel.CategoryId = id;
                return View(viewModel);
            }
            else
            {
                return RedirectToAction("Index", "Category");
            }
        }

        [HttpPost]
        public async Task<ProcessResult<string>> SubmitPhoto(SubmitSinglePhotoViewModel viewModel)
        {
            ProcessResult<string> result = new ProcessResult<string>();

            ProcessResult<bool> categoryStatus = await CategoryIsInRequiredStatus(viewModel.CategoryId, CategoryStatusCodes.SubmittingPhotos);            
            if (!categoryStatus.Success)
                result.AddError(categoryStatus.ErrorMessage);

            if (!viewModel.FileType.ToLower().StartsWith("image"))
                result.AddError("Silly thing. Only an image file type is allowed");

            if (result.Success)
            {
                Photograph photo = await _db.Photographs
                        .FirstOrDefaultAsync(p =>
                            p.Category.CategoryId == viewModel.CategoryId &&
                            p.UserCategoryPhotoNumber == viewModel.PhotoNumber &&
                            p.Photographer.UserName == User.Identity.Name);
                SubmitSinglePhotoViewModelMapper mapper = new SubmitSinglePhotoViewModelMapper();
                ProcessResult<bool> saveResult = null;

                if (photo == null)
                {
                    ApplicationUser user = await _userManager.FindByNameAsync(User.Identity.Name);
                    if (user == null)
                        result.AddError("Unable to find this user");

                    PhotoCategory category = await _db.PhotoCategories.FirstOrDefaultAsync(c => c.CategoryId == viewModel.CategoryId);
                    if (category == null)
                        result.AddError("Unable to find this category");

                    if (result.Success)
                    {
                        photo = mapper.BuildRepositoryModel(viewModel, user, category);
                        saveResult = _db.SaveAdditions(photo);
                    }
                }
                else
                {
                    photo = mapper.BuildRepositoryModel(viewModel, photo);
                    saveResult = _db.SaveUpdates(photo);
                }

                if (result.Success)
                {
                    if (saveResult.Success)
                        result.SetResult(GetImageString(photo.SmallImage));
                    else
                        result.AddError(saveResult.ErrorMessage);
                } 
            }

            return result;
        }

        public async Task<ProcessResult<string>> GetPreviewPhoto(int cId, short pId)
        {
            Photograph photo = await _db.Photographs
                .FirstOrDefaultAsync(p =>
                    p.Category.CategoryId == cId &&
                    p.UserCategoryPhotoNumber == pId &&
                    p.Photographer.UserName == User.Identity.Name);

            ProcessResult<string> result = new ProcessResult<string>();
            if (photo == null)
                result.SetResult(string.Empty);
            else
                result.SetResult(GetImageString(photo.SmallImage));

            return result;
        }

        [HttpPost]
        public async Task<ProcessResult<bool>> RemovePhoto(RemovePhotoViewModel viewModel)
        {
            ProcessResult<bool> result = new ProcessResult<bool>();
            
            ProcessResult<bool> categoryStatus = await CategoryIsInRequiredStatus(viewModel.CategoryId, CategoryStatusCodes.SubmittingPhotos);
            if (!categoryStatus.Success)
                result.AddError(categoryStatus.ErrorMessage);

            if (result.Success)
            {
                Photograph photo = await _db.Photographs
                    .FirstOrDefaultAsync(p =>
                        p.Category.CategoryId == viewModel.CategoryId &&
                        p.UserCategoryPhotoNumber == viewModel.PhotoNumber &&
                        p.Photographer.UserName == User.Identity.Name);

                if (photo != null)
                {
                    result = _db.SaveRemoves(photo);
                }
                else
                {
                    result.AddError("Unable to find a photo with these details");
                } 
            }

            return result;
        }
        #endregion

        #region Vote photos
        public async Task<ProcessResult<string[]>> SubmitVotes([FromBody]VotePhotosViewModel viewModel)
        {
            ProcessResult<string[]> result = new ProcessResult<string[]>();

            if (viewModel.PhotoIds.Length != 3)
                result.AddError("Invalid number of photos voted for");

            ApplicationUser user = null;
            if (result.Success)
            {
                user = await _userManager.FindByNameAsync(User.Identity.Name);
                if (user == null)
                    result.AddError("Unable to find this user");
            }

            PhotoCategory category = null;
            if (result.Success)
            {
                category = _db.PhotoCategories.FirstOrDefault(c => c.CategoryId == viewModel.CategoryId);
                if (category == null)
                    result.AddError("Unable to find this category");
            }

            PhotoVote[] votes = new PhotoVote[3];
            if (result.Success)
            {                
                int position = 0;
                foreach (int photoId in viewModel.PhotoIds)
                {
                    
                    Photograph photo = _db.Photographs
                        .FirstOrDefault(p => p.PhotoId == photoId);
                    if (photo == null)
                    {
                        result.AddError($"Unable to find photo id {photoId}");
                    }
                    else
                    {
                        PhotoVote vote = new PhotoVote()
                        {
                            Position = position + 1,
                            Voter = user,
                            Photo = photo
                        };
                        votes[position] = vote;
                    }
                    position++;
                }
            }

            if (result.Success)
            {                
                _db.PhotoVotes.RemoveRange(_db.PhotoVotes.Where(p => p.Photo.Category.CategoryId == viewModel.CategoryId && p.Voter.UserName == user.UserName));
                ProcessResult<bool> saveResult = _db.SaveAdditions(votes);
                if (!saveResult.Success)
                    result.AddError(saveResult.ErrorMessage);
            }

            if (result.Success)
            {
                result = await GetExistingVotes(viewModel.CategoryId);
            }

            return result;
        }

        public async Task<ProcessResult<string[]>> GetExistingVotes(int id)
        {
            ProcessResult<string[]> result = new ProcessResult<string[]>();

            ApplicationUser user = null;
            if (result.Success)
            {
                user = await _userManager.FindByNameAsync(User.Identity.Name);
                if (user == null)
                    result.AddError("Unable to find this user");
            }

            if (result.Success)
            {
                string[] votes = _db.PhotoVotes
                        .Where(v => v.Photo.Category.CategoryId == id && v.Voter.UserName == user.UserName)
                        .OrderBy(v => v.Position)
                        .Select(v => v.Photo.AnonymousPhotoName)
                        .ToArray();
                result.SetResult(votes);
            }

            return result;
        }
        #endregion

        #region Photo viewing and judging
        public async Task<IActionResult> Index(int id)
        {
            ProcessResult<bool> categoryStatus = await CategoryIsInRequiredStatus(id, CategoryStatusCodes.Judging, CategoryStatusCodes.Completed);

            if (categoryStatus.Success)
            {
                PhotoCategory category = await _db.
                    PhotoCategories
                    .FirstOrDefaultAsync(p => p.CategoryId == id);

                ViewPhotosViewModelMapper mapper = new ViewPhotosViewModelMapper();
                ViewPhotosViewModel viewModel = mapper.BuildViewModel(category);
                return View(viewModel);
            }
            else
            {

JudgeMyPhoto/Views/Category/Add.cshtml
@model Marcware.JudgeMyPhoto.ViewModels.Category.CategoryViewModel

@{
    ViewData["Title"] = "Categories > Add";
}

<div class="row">
    <form asp-action="Add">
        <div class="form-group-row">
            <div class="col-sm-7 offset-4">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            </div>
        </div>
        <input type="hidden" asp-for="CategoryId" />
        <div class="form-group row">
            <div class="col-sm-4">
                <label asp-for="CategoryName" class="app-label"></label>
            </div>
            <div class="col-sm-7">
                <input asp-for="CategoryName" class="app-textbox" />
                <span asp-validation-for="CategoryName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-4">
                <label asp-for="StatusCode" class="app-label"></label>
            </div>
            <div class="col-sm-7">
                <select class="app-select" asp-for="StatusCode" asp-items='@(new SelectList(Model.StatusCodeTypes.ToList(), "Key", "Value", Model.StatusCode))'></select>
                <span asp-validation-for="StatusCode" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-4">
                <label asp-for="StatusText" class="app-label"></label>
            </div>
            <div class="col-sm-7">
                <input asp-for="StatusText" class="app-textbox" />
                <span asp-validation-for="StatusText" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-4">
                <label asp-for="PhotoNamingThemeCode" class="app-label"></label>
            </div>
            <div class="col-sm-7">
                <select class="app-select" asp-for="PhotoNamingThemeCode" asp-items='@(new SelectList(Model.PhotoNamingThemeTypes.ToList(), "Key", "Value", Model.PhotoNamingThemeCode))'></select>
                <span asp-validation-for="PhotoNamingThemeCode" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group col-7 offset-4">
            <input type="submit" value="Save" class="btn btn-primary app-save-button" />
        </div>
    </form>
</div>

JudgeMyPhoto/Views/Category/Delete.cshtml
@model Marcware.JudgeMyPhoto.ViewModels.Category.DeleteCategoryViewModel

@{
    ViewData["Title"] = "JMP > Delete category";
}

<h3>Are you sure you want to delete this category?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CategoryId" />
        <input type="hidden" asp-for="CategoryName" />
        <input type="submit" value="Delete" class="btn btn-danger app-delete-button" /> |
    </form>
</div>

JudgeMyPhoto/Views/Category/Edit.cshtml
@model Marcware.JudgeMyPhoto.ViewModels.Category.CategoryViewModel

@{
    ViewData["Title"] = "Categories > Edit";
}

<div class="row">
    <form asp-action="Edit">
        <div class="form-group-row">
            <div class="col-sm-7 offset-4">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            </div>
        </div>
        <input type="hidden" asp-for="CategoryId" />
        <div class="form-group row">
            <div class="col-sm-4">
                <label asp-for="CategoryName" class="app-label"></label>
            </div>
            <div class="col-sm-7">
                <input asp-for="CategoryName" class="app-textbox" />
                <span asp-validation-for="CategoryName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-4">
                <label asp-for="StatusCode" class="app-label"></label>
            </div>
            <div class="col-sm-7">
                <select class="app-select" asp-for="StatusCode" asp-items='@(new SelectList(Model.StatusCodeTypes.ToList(), "Key", "Value", Model.StatusCode))'></select>
                <span asp-validation-for="StatusCode" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-4">
                <label asp-for="StatusText" class="app-label"></label>
            </div>
            <div class="col-sm-7">
                <input asp-for="StatusText" class="app-textbox" />
                <span asp-validation-for="StatusText" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-4">
                <label asp-for="PhotoNamingThemeCode" class="app-label"></label>
            </div>
            <div class="col-sm-7">
                <select class="app-select" asp-for="PhotoNamingThemeCode" asp-items='@(new SelectList(Model.PhotoNamingThemeTypes.ToList(), "Key", "Value", Model.PhotoNamingThemeCode))'></select>
                <span asp-validation-for="PhotoNamingThemeCode" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group col-7 offset-4">
            <input type="submit" value="Save" class="btn btn-primary app-save-button" />
        </div>
    </form>
</div>

JudgeMyPhoto/Views/Category/Index.cshtml
@model Marcware.JudgeMyPhoto.ViewModels.Category.CategoryListViewModel
@using Microsoft.AspNetCore.Identity;
@using Marcware.JudgeMyPhoto.Entities.Models;
@using Marcware.JudgeMyPhoto.Constants;
@inject SignInManager<ApplicationUser> signInManager;

@{
    ViewData["Title"] = "JMP > Category list";
}

@if (signInManager.IsSignedIn(User) && User.IsInRole(JudgeMyPhotoRoles.Admin))
{
    <p>
        <a asp-action="Add" class="btn btn-primary btn-sm active app-add-button">Create New</a>
    </p>
}
   
<div class="row info-table-header-row">
    <div class="col-sm-3">
        Category
    </div>
    <div class="col-sm-6">
        Status
    </div>
    <div class="col-sm-3">            
    </div>
</div>

@foreach (var item in Model.Items)
{
    <div class="row info-table-data-row">
        <div class="col-sm-3">
            @Html.DisplayFor(_ => item.CategoryName)
        </div>
        <div class="col-sm-6">
            @Html.DisplayFor(_ => item.StatusText)
        </div>
        <div class="col-sm-3">
            @if (item.StatusCode == CategoryStatusCodes.SubmittingPhotos && signInManager.IsSignedIn(User) && User.IsInRole(JudgeMyPhotoRoles.Photographer))
            {
                <a href="@(Url.Action("Submit", "Photos", new { id = item.CategoryId, v = 1 }))" class="btn btn-primary btn-sm active" role="button" aria-disabled="true">Submit photos</a>
            }
            @if (item.StatusCode == CategoryStatusCodes.Judging && signInManager.IsSignedIn(User) && User.IsInRole(JudgeMyPhotoRoles.Photographer))
            {
                <a href="@(Url.Action("Index", "Photos", new { id = item.CategoryId, v = 1 }))" class="btn btn-primary btn-sm active" role="button" aria-disabled="true">Judge photos</a>
            }
            @if (item.StatusCode == CategoryStatusCodes.Completed && signInManager.IsSignedIn(User) && User.IsInRole(JudgeMyPhotoRoles.Photographer))
            {
                <a href="@(Url.Action("Index", "Photos", new { id = item.CategoryId, v = 1 }))" class="btn btn-primary btn-sm active" role="button" aria-disabled="true">View photos</a>
            }
            @if (signInManager.IsSignedIn(User) && User.IsInRole(JudgeMyPhotoRoles.Admin))
            {
                <a href="@(Url.Action("Edit", new { id = item.CategoryId }))" class="btn btn-primary btn-sm active" role="button" aria-disabled="true">Edit</a>
                <a href="@(Url.Action("Delete", new { id = item.CategoryId }))" class="btn btn-danger btn-sm active" role="button" aria-disabled="true">Delete</a>
            }
        </div>
    </div>
}